DROP TABLE IF EXISTS employee;
CREATE TABLE employee (employee_id INT AUTO_INCREMENT PRIMARY KEY, employee_name VARCHAR(20), employee_address VARCHAR(50));
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;
SELECT * FROM EMPLOYEE;